POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstName": "Francesco",
    "lastName": "Di Donato",
    "email": "didonato.fr@gmail.com",
    "password": "ossobuco"
}

###

GET http://localhost:3000/api/posts